name: Config_checker

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
check-format:
  runs-on: windows-latest

      steps:
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
          with:
          dotnet-version: '7.0.x'
       
      - name: Check out code
        uses: actions/checkout@v3
       
      - name: Run dotnet format
        run: dotnet format
