name: Config_checker

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm conf_check
